list: $/pensoft/impact/models/group/columns.yaml
modelClass: Pensoft\Impact\Models\Group
title: Groups
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/impact/groups/update/:id'
